package html

import (
	"encoding/base64"
	"encoding/json"
	stdhtml "html"
	"strconv"
	"strings"
)

// RenderAnimatedPlaybackHTML generates HTML that replays terminal output chunks over time.
func RenderAnimatedPlaybackHTML(frames []PlaybackFrame, title string, footerLink FooterLink, markers []AnimationMarker, cues []AnimationCue) (string, error) {
	if frames == nil {
		frames = []PlaybackFrame{}
	}
	if markers == nil {
		markers = []AnimationMarker{}
	}
	if cues == nil {
		cues = []AnimationCue{}
	}

	framesJSON, err := json.Marshal(frames)
	if err != nil {
		return "", err
	}
	markersJSON, err := json.Marshal(markers)
	if err != nil {
		return "", err
	}
	cuesJSON, err := json.Marshal(cues)
	if err != nil {
		return "", err
	}

	framesBase64 := base64.StdEncoding.EncodeToString(framesJSON)
	markersBase64 := base64.StdEncoding.EncodeToString(markersJSON)
	cuesBase64 := base64.StdEncoding.EncodeToString(cuesJSON)

	if title == "" {
		title = "Terminal"
	}
	escapedTitle := stdhtml.EscapeString(title)

	footerHTML := `generated by <a href="https://github.com/choonkeat/record-tui" target="_blank" rel="noopener noreferrer">record-tui</a>`
	if footerLink.Text != "" && footerLink.URL != "" {
		footerHTML += ` x <a href="` + stdhtml.EscapeString(footerLink.URL) + `" target="_blank" rel="noopener noreferrer">` + stdhtml.EscapeString(footerLink.Text) + `</a>`
	}

	var markerButtons strings.Builder
	for _, marker := range markers {
		markerButtons.WriteString(`<button type="button" class="animation-marker" data-time="`)
		markerButtons.WriteString(strconv.FormatFloat(marker.Timestamp, 'f', 3, 64))
		markerButtons.WriteString(`">`)
		markerButtons.WriteString(stdhtml.EscapeString(marker.Label))
		markerButtons.WriteString(`</button>`)
	}
	for _, cue := range cues {
		if cue.Label == "" {
			continue
		}
		markerButtons.WriteString(`<button type="button" class="animation-marker animation-cue" data-time="`)
		markerButtons.WriteString(strconv.FormatFloat(cue.Timestamp, 'f', 3, 64))
		markerButtons.WriteString(`">`)
		markerButtons.WriteString(stdhtml.EscapeString(cue.Label))
		markerButtons.WriteString(`</button>`)
	}

	htmlDoc := `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>` + escapedTitle + `</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@xterm/xterm@5.5.0/css/xterm.css" />
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    html, body {
      width: 100%;
      min-height: 100%;
      background: #1e1e1e;
      color: #d4d4d4;
      font-family: 'SF Mono', 'Menlo', 'Consolas', 'Monaco', 'Courier New', monospace;
    }

    #animation-controls {
      position: sticky;
      top: 0;
      z-index: 10;
      display: grid;
      grid-template-columns: auto auto minmax(160px, 1fr) auto;
      gap: 10px;
      align-items: center;
      padding: 10px 12px;
      background: #252526;
      border-bottom: 1px solid rgba(212, 212, 212, 0.16);
    }

    #animation-play,
    #animation-speed,
    .animation-marker {
      min-height: 32px;
      padding: 0 10px;
      border: 1px solid rgba(212, 212, 212, 0.22);
      border-radius: 6px;
      background: #333333;
      color: #f2f2f2;
      font: inherit;
      font-size: 13px;
    }

    #animation-play {
      min-width: 72px;
      cursor: pointer;
    }

    #animation-speed {
      cursor: pointer;
    }

    #animation-timeline {
      width: 100%;
      min-width: 0;
    }

    #animation-time {
      min-width: 112px;
      text-align: right;
      color: #bbbbbb;
      font-size: 12px;
    }

    #animation-markers {
      display: flex;
      gap: 8px;
      flex-wrap: wrap;
      padding: 8px 12px;
      background: #202020;
      border-bottom: 1px solid rgba(212, 212, 212, 0.12);
    }

    .animation-marker {
      max-width: 260px;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      cursor: pointer;
    }

    #terminal {
      width: 100%;
      min-height: 320px;
      display: block;
    }

    #footer {
      margin-top: 24px;
      padding: 12px 24px;
      text-align: right;
      font-size: 12px;
      color: #888888;
      border-top: 1px solid rgba(212, 212, 212, 0.1);
    }

    #footer a {
      color: #e0e0e0;
      text-decoration: none;
    }

    #loading {
      padding: 24px;
      color: #888888;
    }

    @media (max-width: 720px) {
      #animation-controls {
        grid-template-columns: auto auto 1fr;
      }

      #animation-time {
        grid-column: 1 / -1;
        text-align: left;
      }
    }
  </style>
</head>
<body>
  <div id="animation-controls">
    <button id="animation-play" type="button">Play</button>
    <select id="animation-speed" aria-label="Playback speed">
      <option value="0.25">0.25x</option>
      <option value="0.5">0.5x</option>
      <option value="1" selected>1x</option>
      <option value="2">2x</option>
      <option value="5">5x</option>
      <option value="10">10x</option>
    </select>
    <input id="animation-timeline" type="range" min="0" max="0" step="0.001" value="0" aria-label="Timeline" />
    <output id="animation-time">0:00 / 0:00</output>
  </div>
  <div id="animation-markers">` + markerButtons.String() + `</div>
  <div id="loading">Loading...</div>
  <div id="terminal"></div>
  <div id="footer">` + footerHTML + `</div>

  <script src="https://cdn.jsdelivr.net/npm/@xterm/xterm@5.5.0/lib/xterm.js"></script>
  <script>
    const framesBase64 = '` + framesBase64 + `';
    const framesJson = new TextDecoder().decode(
      Uint8Array.from(atob(framesBase64), c => c.charCodeAt(0))
    );
    const frames = JSON.parse(framesJson);

    const animationMarkersBase64 = '` + markersBase64 + `';
    const animationMarkersJson = new TextDecoder().decode(
      Uint8Array.from(atob(animationMarkersBase64), c => c.charCodeAt(0))
    );
    const animationMarkers = JSON.parse(animationMarkersJson);

    const animationCuesBase64 = '` + cuesBase64 + `';
    const animationCuesJson = new TextDecoder().decode(
      Uint8Array.from(atob(animationCuesBase64), c => c.charCodeAt(0))
    );
    const animationCues = JSON.parse(animationCuesJson).sort((a, b) => a.timestamp - b.timestamp);

    const finalContent = frames.map(frame => frame.content).join('');
    const normalized = finalContent.split('\r\n').join('\n').split('\r').join('\n');
    const lines = normalized.split('\n');
    let maxLineLength = 0;
    for (const line of lines) {
      maxLineLength = Math.max(maxLineLength, line.length);
    }
    const cols = Math.min(Math.max(maxLineLength, 80), 240);
    const rows = Math.max(Math.min(lines.length + 2, 120), 24);

    const terminalDiv = document.getElementById('terminal');
    const xterm = new Terminal({
      cols,
      rows,
      fontSize: 15,
      cursorBlink: false,
      disableStdin: true,
      altClickMovesCursor: false,
      scrollOnUserInput: false,
      scrollback: 100000,
      theme: {
        background: '#1e1e1e',
        foreground: '#d4d4d4',
      },
      allowAlternateScreen: false,
    });
    xterm.open(terminalDiv);
    xterm.attachCustomKeyEventHandler((event) => {
      if ((event.metaKey || event.ctrlKey) && event.key === 'c') {
        return true;
      }
      return false;
    });
    xterm.attachCustomWheelEventHandler(() => false);

    const playButton = document.getElementById('animation-play');
    const speedSelect = document.getElementById('animation-speed');
    const timeline = document.getElementById('animation-timeline');
    const timeLabel = document.getElementById('animation-time');
    const totalTime = frames.length > 0 ? frames[frames.length - 1].timestamp : 0;
    timeline.max = String(totalTime);

    let playing = false;
    let speed = Number(speedSelect.value);
    let frameIndex = 0;
    let currentTime = 0;
    let startedAt = 0;
    let startedFrom = 0;
    let playToken = 0;
    let cueIndex = 0;

    function formatTime(seconds) {
      if (!Number.isFinite(seconds)) {
        seconds = 0;
      }
      const minutes = Math.floor(seconds / 60);
      const remaining = Math.floor(seconds % 60).toString().padStart(2, '0');
      return minutes + ':' + remaining;
    }

    function updateControls(time) {
      currentTime = Math.min(Math.max(time, 0), totalTime);
      timeline.value = String(currentTime);
      timeLabel.textContent = formatTime(currentTime) + ' / ' + formatTime(totalTime);
      playButton.textContent = playing ? 'Pause' : 'Play';
    }

    function setSpeed(nextSpeed) {
      if (!Number.isFinite(nextSpeed) || nextSpeed <= 0) {
        return;
      }
      speed = nextSpeed;
      const value = String(nextSpeed);
      if (![...speedSelect.options].some(option => option.value === value)) {
        const option = document.createElement('option');
        option.value = value;
        option.textContent = value + 'x';
        speedSelect.appendChild(option);
      }
      speedSelect.value = value;
      if (playing) {
        startedFrom = currentTime;
        startedAt = performance.now();
      }
    }

    function renderUntil(time) {
      while (frameIndex < frames.length && frames[frameIndex].timestamp <= time) {
        xterm.write(frames[frameIndex].content);
        frameIndex++;
      }
      xterm.scrollToBottom();
    }

    function resetTo(time) {
      xterm.reset();
      frameIndex = 0;
      cueIndex = animationCues.findIndex(cue => cue.timestamp > time);
      if (cueIndex < 0) {
        cueIndex = animationCues.length;
      }
      currentTime = 0;
      renderUntil(time);
      updateControls(time);
    }

    function applyCuesUntil(time) {
      while (cueIndex < animationCues.length && animationCues[cueIndex].timestamp <= time) {
        const cue = animationCues[cueIndex++];
        if (cue.speed > 0) {
          setSpeed(cue.speed);
        }
        if (cue.pause > 0) {
          const pauseAt = Math.min(Math.max(cue.timestamp, 0), totalTime);
          renderUntil(pauseAt);
          playing = false;
          playToken++;
          const resumeToken = playToken;
          updateControls(pauseAt);
          window.setTimeout(() => {
            if (!playing && playToken === resumeToken) {
              playFrom(pauseAt);
            }
          }, cue.pause * 1000);
          return true;
        }
      }
      return false;
    }

    function stopPlayback(time) {
      playing = false;
      playToken++;
      updateControls(time);
    }

    function tick(now, token) {
      if (!playing || token !== playToken) {
        return;
      }
      const elapsed = ((now - startedAt) / 1000) * speed;
      const nextTime = Math.min(startedFrom + elapsed, totalTime);
      const targetTime = cueIndex < animationCues.length && animationCues[cueIndex].timestamp <= nextTime
        ? animationCues[cueIndex].timestamp
        : nextTime;
      renderUntil(targetTime);
      updateControls(targetTime);
      if (applyCuesUntil(targetTime)) {
        return;
      }
      if (targetTime >= totalTime) {
        stopPlayback(totalTime);
        return;
      }
      requestAnimationFrame((next) => tick(next, token));
    }

    function playFrom(time) {
      playToken++;
      const token = playToken;
      resetTo(time);
      startedFrom = currentTime;
      startedAt = performance.now();
      playing = true;
      updateControls(currentTime);
      requestAnimationFrame((now) => tick(now, token));
    }

    function pausePlayback() {
      playing = false;
      playToken++;
      updateControls(currentTime);
    }

    playButton.addEventListener('click', () => {
      if (playing) {
        pausePlayback();
      } else if (currentTime >= totalTime) {
        playFrom(0);
      } else {
        playFrom(currentTime);
      }
    });

    speedSelect.addEventListener('change', () => {
      setSpeed(Number(speedSelect.value));
    });

    timeline.addEventListener('input', () => {
      const nextTime = Number(timeline.value);
      const wasPlaying = playing;
      playing = false;
      resetTo(nextTime);
      if (wasPlaying) {
        playFrom(nextTime);
      }
    });

    document.querySelectorAll('.animation-marker').forEach((button) => {
      button.addEventListener('click', () => {
        playFrom(Number(button.dataset.time));
      });
    });

    document.addEventListener('copy', (event) => {
      const selection = xterm.getSelection();
      if (selection) {
        const cleaned = selection.split('\n').map(line => line.trimEnd()).join('\n');
        event.clipboardData.setData('text/plain', cleaned);
        event.preventDefault();
      }
    });

    document.getElementById('loading').style.display = 'none';
    updateControls(0);
    document.dispatchEvent(new Event('xterm-ready'));
  </script>
</body>
</html>`

	return htmlDoc, nil
}
